// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCAvgCV1XZR61MVsITfzvNsaI58KuW-n-I',
    appId: '1:184062163822:web:7d8ec2b071b6f42cdadf7f',
    messagingSenderId: '184062163822',
    projectId: 'hum-saya',
    authDomain: 'hum-saya.firebaseapp.com',
    databaseURL: 'https://hum-saya-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'hum-saya.appspot.com',
    measurementId: 'G-MSTY7D9P56',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAQkVVreqDBTS5ZMrCx_tbfy7mx8B15lBM',
    appId: '1:184062163822:android:152a227eae46f1d9dadf7f',
    messagingSenderId: '184062163822',
    projectId: 'hum-saya',
    databaseURL: 'https://hum-saya-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'hum-saya.appspot.com',
  );

}